name: Update Funding Data

on:
  schedule:
    # Run daily at 6am UTC (10pm PST, 1am EST)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedparser
      
      - name: Run funding scraper
        run: python scraper_v2.py
        continue-on-error: true  # Don't fail if one source is down
      
      - name: Run VC portfolio scraper
        run: python vc_scraper.py
        continue-on-error: true
      
      - name: Run job scraper
        run: python job_scraper.py
        continue-on-error: true
      
      - name: Rebuild site with new data
        run: python build_site.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "🔄 Update funding data $(date +'%Y-%m-%d')" && git push)
